name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311haee01d2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py311h49ec1c0_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - camelot-py==1.0.9
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cmasher==1.9.2
      - colorspacious==1.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.60.1
      - importlib-resources==6.5.2
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - matplotlib==3.10.7
      - nibabel==5.3.2
      - numpy==2.2.6
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pdf2image==1.17.0
      - pdfminer-six==20251107
      - pillow==12.0.0
      - ptitprince==0.3.1
      - pycparser==2.23
      - pyparsing==3.2.5
      - pypdf==3.17.4
      - pypdfium2==5.1.0
      - pytesseract==0.3.13
      - python-docx==1.2.0
      - pytz==2025.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - tabulate==0.9.0
      - tzdata==2025.2
prefix: /home/ndzinal/miniconda3/envs/myenv
